version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sentiment_analysis
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: ./app
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URI: mysql+mysqlconnector://user:password@db:3306/sentiment_analysis
    depends_on:
      - db
    volumes:
      - ./app:/app
    command: ["./entrypoint.sh"]

volumes:
  mysql_data: