"""empty message

Revision ID: 53ebc80c136e
Revises: be0236373cb1
Create Date: 2025-02-21 12:44:11.263385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ebc80c136e'
down_revision = 'be0236373cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        # Only create the text index with length specification
        batch_op.create_index(batch_op.f('ix_tweet_text'), ['text(255)'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tweet_text'))
    # ### end Alembic commands ###
