"""empty message

Revision ID: be0236373cb1
Revises: 6b4a399d00f7
Create Date: 2025-02-20 23:21:17.937417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0236373cb1'
down_revision = '6b4a399d00f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_tweet_negative'), ['negative'], unique=False)
        batch_op.create_index(batch_op.f('ix_tweet_positive'), ['positive'], unique=False)
        batch_op.create_index(batch_op.f('ix_tweet_text'), ['text'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tweet_text'))
        batch_op.drop_index(batch_op.f('ix_tweet_positive'))
        batch_op.drop_index(batch_op.f('ix_tweet_negative'))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
